-- Add Foreign Keys to enforce referential integrity
-- Migration: 0026_add_foreign_keys.sql

-- Companies
-- Note: SQLite doesn't support ALTER TABLE ADD CONSTRAINT for FK
-- We need to recreate tables with FK constraints
-- For now, we document the FK relationships in schema.ts
-- Real FK enforcement will be done in schema.ts with Drizzle

-- This migration serves as documentation of FK relationships:

-- companies.owner_id → users.id (ON DELETE RESTRICT)
-- managers.user_id → users.id (ON DELETE CASCADE)
-- managers.company_id → companies.id (ON DELETE CASCADE)
-- company_cars.company_id → companies.id (ON DELETE RESTRICT)
-- company_cars.template_id → car_templates.id (ON DELETE SET NULL)
-- company_cars.color_id → colors.id (ON DELETE SET NULL)
-- company_cars.fuel_type_id → fuel_types.id (ON DELETE SET NULL)
-- contracts.company_car_id → company_cars.id (ON DELETE RESTRICT)
-- contracts.client_id → users.id (ON DELETE RESTRICT)
-- contracts.manager_id → users.id (ON DELETE SET NULL)
-- contracts.pickup_district_id → districts.id (ON DELETE SET NULL)
-- contracts.return_district_id → districts.id (ON DELETE SET NULL)
-- contracts.booking_id → bookings.id (ON DELETE SET NULL)
-- bookings.company_car_id → company_cars.id (ON DELETE RESTRICT)
-- bookings.client_id → users.id (ON DELETE RESTRICT)
-- bookings.manager_id → users.id (ON DELETE SET NULL)
-- bookings.pickup_district_id → districts.id (ON DELETE SET NULL)
-- bookings.return_district_id → districts.id (ON DELETE SET NULL)
-- payments.contract_id → contracts.id (ON DELETE CASCADE)
-- payments.payment_type_id → payment_types.id (ON DELETE RESTRICT)
-- payments.currency_id → currencies.id (ON DELETE RESTRICT)
-- payments.created_by → users.id (ON DELETE SET NULL)
-- payment_types.company_id → companies.id (ON DELETE CASCADE)
-- currencies.company_id → companies.id (ON DELETE CASCADE)
-- maintenance_history.company_car_id → company_cars.id (ON DELETE CASCADE)
-- calendar_events.company_id → companies.id (ON DELETE CASCADE)
-- calendar_events.created_by → users.id (ON DELETE SET NULL)
-- audit_logs.user_id → users.id (ON DELETE SET NULL)
-- audit_logs.company_id → companies.id (ON DELETE SET NULL)

-- SQLite FK constraints are defined in schema.ts using Drizzle ORM
-- This ensures type-safe FK relationships at the application level
