// UI Components (app/components/ui/)
export { default as Button } from './ui/Button'
export { Card } from './dashboard/Card'
export { default as Modal } from './dashboard/Modal'
export { default as ConfirmModal } from './ui/ConfirmModal'
export { default as DataTable } from './ui/DataTable'
export { Pagination } from './dashboard/Pagination'
export { default as Tabs } from './dashboard/Tabs'
export type { Tab } from './dashboard/Tabs'
export { default as Loader } from './dashboard/Loader'
export { default as EmptyState } from './dashboard/EmptyState'
export { default as StatusBadge } from './dashboard/StatusBadge'
export { default as IconBadge } from './ui/IconBadge'
export { default as IdBadge } from './dashboard/IdBadge'
export { BackButton } from './dashboard/BackButton'
export { Breadcrumb } from './ui/Breadcrumb'
export { default as ToastContainer } from './ui/ToastContainer'
export { default as ToastItem } from './dashboard/ToastItem'
export { default as FormField } from './dashboard/FormField'
export { default as FormSection } from './dashboard/FormSection'
export { default as FormBox } from './dashboard/FormBox'
export { default as FormSelect } from './dashboard/FormSelect'
export { default as FormActions } from './dashboard/FormActions'
export { default as FormGrid } from './ui/FormGrid'
export { default as ReadOnlyField } from './dashboard/ReadOnlyField'
export { default as Toggle } from './ui/Toggle'
export { default as DeleteButton } from './dashboard/DeleteButton'
export { Input } from './dashboard/Input'
export { Select } from './dashboard/Select'
export { Textarea } from './dashboard/Textarea'
export { default as PhotoUpload } from './dashboard/PhotoUpload'
export { default as DocumentPhotosUpload } from './dashboard/DocumentPhotosUpload'
export { default as PhotoUploadSection } from './ui/PhotoUploadSection'
export { default as PhotoUploadMultiple } from './ui/PhotoUploadMultiple'
export { default as Avatar } from './dashboard/Avatar'
export { default as ProfileHeader } from './dashboard/ProfileHeader'
export { default as DocumentPreview } from './dashboard/DocumentPreview'
export type { DocumentPhoto } from './dashboard/DocumentPreview'

// Layout Components
export { default as PageHeader } from './dashboard/PageHeader'
export { PageContent } from './ui/PageContent'
export { default as PageActions } from './ui/PageActions'
export { default as Section } from './ui/Section'
export { default as ListPage } from './ui/ListPage'

// Detail Components
export { default as DetailView } from './ui/DetailView'
export { default as DetailGrid } from './ui/DetailGrid'
export { default as DetailField } from './ui/DetailField'

// Dashboard Components
export { default as StatCard } from './ui/StatCard'
export { default as ChartsWidget } from './ui/ChartsWidget'
export { default as TasksWidget } from './dashboard/TasksWidget'
export { default as QuickActions } from './ui/QuickActions'
export { default as RecentActivity } from './ui/RecentActivity'
export { default as UpcomingEventsWidget } from './ui/UpcomingEventsWidget'
export { default as LocationsHealth } from './ui/LocationsHealth'

// Dashboard-specific Forms (app/components/dashboard/)
export { BrandForm } from './dashboard/BrandForm'
export { CarModelForm } from './dashboard/CarModelForm'
export { CarTemplateForm } from './dashboard/CarTemplateForm'
export { ColorForm } from './dashboard/ColorForm'
export { CurrencyForm } from './dashboard/CurrencyForm'
export { DistrictForm } from './dashboard/DistrictForm'
export { default as MaintenanceForm } from './dashboard/MaintenanceForm'
export { default as MaintenanceModal } from './dashboard/MaintenanceModal'
export { default as MaintenanceHistory } from './dashboard/MaintenanceHistory'
export { PaymentStatusForm } from './dashboard/PaymentStatusForm'
export { PaymentTypeForm } from './dashboard/PaymentTypeForm'
export { default as PaymentsTable } from './dashboard/PaymentsTable'
export { default as SeasonalPricingTable } from './dashboard/SeasonalPricingTable'
export { TaskForm } from './dashboard/TaskForm'
export { default as RoleSwitcher } from './dashboard/RoleSwitcher'
export { default as WeeklySchedule } from './dashboard/WeeklySchedule'
export { default as HolidaysManager } from './dashboard/HolidaysManager'

// Profile Components
export { default as ProfileForm } from './dashboard/ProfileForm'

// Layout Components (app/components/layout/)
export { Layout } from './layout/DashboardLayout'
export { default as Sidebar } from './dashboard/Sidebar'
export { default as Topbar } from './dashboard/Topbar'
export { TopNavigation } from './dashboard/TopNavigation'
