// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/register-partner": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/assets/*": {
    params: {
      "*": string;
    };
  };
  "/become-a-host": {
    params: {};
  };
  "/why-choose-phuket-ride": {
    params: {};
  };
  "/gift-cards": {
    params: {};
  };
  "/contact-support": {
    params: {};
  };
  "/legal": {
    params: {};
  };
  "/insurance-protection": {
    params: {};
  };
  "/host-tools": {
    params: {};
  };
  "/carculator": {
    params: {};
  };
  "/search-cars": {
    params: {};
  };
  "/company/:slug": {
    params: {
      "slug": string;
    };
  };
  "/cars/:id": {
    params: {
      "id": string;
    };
  };
  "/cars/:id/checkout": {
    params: {
      "id": string;
    };
  };
  "/booking-confirmation": {
    params: {};
  };
  "/booking-confirmation/:id": {
    params: {
      "id": string;
    };
  };
  "/api/search-events": {
    params: {};
  };
  "/api/metrics/dashboard-charts": {
    params: {};
  };
  "/api/calendar-events": {
    params: {};
  };
  "/api/car-templates/:id/features": {
    params: {
      "id": string;
    };
  };
  "/home": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/companies/create": {
    params: {};
  };
  "/companies/:companyId": {
    params: {
      "companyId": string;
    };
  };
  "/companies/:companyId/edit": {
    params: {
      "companyId": string;
    };
  };
  "/users": {
    params: {};
  };
  "/users/create": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/users/:userId/edit": {
    params: {
      "userId": string;
    };
  };
  "/cars": {
    params: {};
  };
  "/cars/create": {
    params: {};
  };
  "/cars/:id/content": {
    params: {
      "id": string;
    };
  };
  "/cars/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/brands": {
    params: {};
  };
  "/brands/create": {
    params: {};
  };
  "/models": {
    params: {};
  };
  "/models/create": {
    params: {};
  };
  "/car-templates": {
    params: {};
  };
  "/car-templates/create": {
    params: {};
  };
  "/car-templates/:id": {
    params: {
      "id": string;
    };
  };
  "/car-templates/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/payments": {
    params: {};
  };
  "/payments/create": {
    params: {};
  };
  "/payment-statuses": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/districts": {
    params: {};
  };
  "/hotels": {
    params: {};
  };
  "/durations": {
    params: {};
  };
  "/seasons": {
    params: {};
  };
  "/colors": {
    params: {};
  };
  "/colors/new": {
    params: {};
  };
  "/colors/:colorId/edit": {
    params: {
      "colorId": string;
    };
  };
  "/reports": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/contracts": {
    params: {};
  };
  "/contracts/:id/close": {
    params: {
      "id": string;
    };
  };
  "/contracts/new": {
    params: {};
  };
  "/contracts/:id": {
    params: {
      "id": string;
    };
  };
  "/contracts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/calendar": {
    params: {};
  };
  "/calendar/new": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/bookings": {
    params: {};
  };
  "/bookings/create": {
    params: {};
  };
  "/bookings/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/my-bookings": {
    params: {};
  };
  "/my-contracts": {
    params: {};
  };
  "/my-contracts/:id": {
    params: {
      "id": string;
    };
  };
  "/my-payments": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/register-partner" | "/logout" | "/assets/*" | "/become-a-host" | "/why-choose-phuket-ride" | "/gift-cards" | "/contact-support" | "/legal" | "/insurance-protection" | "/host-tools" | "/carculator" | "/search-cars" | "/company/:slug" | "/cars/:id" | "/cars/:id/checkout" | "/booking-confirmation" | "/booking-confirmation/:id" | "/api/search-events" | "/api/metrics/dashboard-charts" | "/api/calendar-events" | "/api/car-templates/:id/features" | "/home" | "/companies" | "/companies/create" | "/companies/:companyId" | "/companies/:companyId/edit" | "/users" | "/users/create" | "/users/:userId" | "/users/:userId/edit" | "/cars" | "/cars/create" | "/cars/:id/content" | "/cars/:id/edit" | "/brands" | "/brands/create" | "/models" | "/models/create" | "/car-templates" | "/car-templates/create" | "/car-templates/:id" | "/car-templates/:id/edit" | "/payments" | "/payments/create" | "/payment-statuses" | "/locations" | "/districts" | "/hotels" | "/durations" | "/seasons" | "/colors" | "/colors/new" | "/colors/:colorId/edit" | "/reports" | "/logs" | "/contracts" | "/contracts/:id/close" | "/contracts/new" | "/contracts/:id" | "/contracts/:id/edit" | "/calendar" | "/calendar/new" | "/settings" | "/bookings" | "/bookings/create" | "/bookings/:id" | "/profile" | "/profile/edit" | "/my-bookings" | "/my-contracts" | "/my-contracts/:id" | "/my-payments" | "/notifications";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/register-partner.tsx": {
    id: "routes/register-partner";
    page: "/register-partner";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/assets.$.tsx": {
    id: "routes/assets.$";
    page: "/assets/*";
  };
  "routes/become-a-host.tsx": {
    id: "routes/become-a-host";
    page: "/become-a-host";
  };
  "routes/why-choose-phuket-ride.tsx": {
    id: "routes/why-choose-phuket-ride";
    page: "/why-choose-phuket-ride";
  };
  "routes/gift-cards.tsx": {
    id: "routes/gift-cards";
    page: "/gift-cards";
  };
  "routes/contact-support.tsx": {
    id: "routes/contact-support";
    page: "/contact-support";
  };
  "routes/legal.tsx": {
    id: "routes/legal";
    page: "/legal";
  };
  "routes/insurance-protection.tsx": {
    id: "routes/insurance-protection";
    page: "/insurance-protection";
  };
  "routes/host-tools.tsx": {
    id: "routes/host-tools";
    page: "/host-tools";
  };
  "routes/carculator.tsx": {
    id: "routes/carculator";
    page: "/carculator";
  };
  "routes/search-cars.tsx": {
    id: "routes/search-cars";
    page: "/search-cars";
  };
  "routes/company.$slug.tsx": {
    id: "routes/company.$slug";
    page: "/company/:slug";
  };
  "routes/cars.$id.tsx": {
    id: "routes/cars.$id";
    page: "/cars/:id";
  };
  "routes/cars.$id.checkout.tsx": {
    id: "routes/cars.$id.checkout";
    page: "/cars/:id/checkout";
  };
  "routes/booking-confirmation.tsx": {
    id: "routes/booking-confirmation";
    page: "/booking-confirmation";
  };
  "routes/booking-confirmation.$id.tsx": {
    id: "routes/booking-confirmation.$id";
    page: "/booking-confirmation/:id";
  };
  "routes/api.search-events.tsx": {
    id: "routes/api.search-events";
    page: "/api/search-events";
  };
  "routes/api.metrics.dashboard-charts.tsx": {
    id: "routes/api.metrics.dashboard-charts";
    page: "/api/metrics/dashboard-charts";
  };
  "routes/api.calendar-events.tsx": {
    id: "routes/api.calendar-events";
    page: "/api/calendar-events";
  };
  "routes/api.car-templates.$id.features.tsx": {
    id: "routes/api.car-templates.$id.features";
    page: "/api/car-templates/:id/features";
  };
  "routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/home" | "/companies" | "/companies/create" | "/companies/:companyId" | "/companies/:companyId/edit" | "/users" | "/users/create" | "/users/:userId" | "/users/:userId/edit" | "/cars" | "/cars/create" | "/cars/:id" | "/cars/:id/content" | "/cars/:id/edit" | "/brands" | "/brands/create" | "/models" | "/models/create" | "/car-templates" | "/car-templates/create" | "/car-templates/:id" | "/car-templates/:id/edit" | "/payments" | "/payments/create" | "/payment-statuses" | "/locations" | "/districts" | "/hotels" | "/durations" | "/seasons" | "/colors" | "/colors/new" | "/colors/:colorId/edit" | "/reports" | "/logs" | "/contracts" | "/contracts/:id/close" | "/contracts/new" | "/contracts/:id" | "/contracts/:id/edit" | "/calendar" | "/calendar/new" | "/settings" | "/bookings" | "/bookings/create" | "/bookings/:id" | "/profile" | "/profile/edit" | "/my-bookings" | "/my-contracts" | "/my-contracts/:id" | "/my-payments" | "/notifications";
  };
  "routes/dashboard-home.tsx": {
    id: "routes/dashboard-home";
    page: "/home";
  };
  "routes/companies.tsx": {
    id: "routes/companies";
    page: "/companies";
  };
  "routes/companies.create.tsx": {
    id: "routes/companies.create";
    page: "/companies/create";
  };
  "routes/admin-companies.$companyId.tsx": {
    id: "routes/admin-companies.$companyId";
    page: "/companies/:companyId";
  };
  "routes/companies.edit.tsx": {
    id: "routes/companies.edit";
    page: "/companies/:companyId/edit";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/users.create.tsx": {
    id: "routes/users.create";
    page: "/users/create";
  };
  "routes/users.$userId.tsx": {
    id: "routes/users.$userId";
    page: "/users/:userId";
  };
  "routes/users.$userId.edit.tsx": {
    id: "routes/users.$userId.edit";
    page: "/users/:userId/edit";
  };
  "routes/cars.tsx": {
    id: "routes/cars";
    page: "/cars";
  };
  "routes/cars.create.tsx": {
    id: "routes/cars.create";
    page: "/cars/create";
  };
  "routes/admin-cars.$id.tsx": {
    id: "routes/admin-cars.$id";
    page: "/cars/:id";
  };
  "routes/cars.$id.content.tsx": {
    id: "routes/cars.$id.content";
    page: "/cars/:id/content";
  };
  "routes/cars.$id.edit.tsx": {
    id: "routes/cars.$id.edit";
    page: "/cars/:id/edit";
  };
  "routes/brands.tsx": {
    id: "routes/brands";
    page: "/brands";
  };
  "routes/brands.create.tsx": {
    id: "routes/brands.create";
    page: "/brands/create";
  };
  "routes/models.tsx": {
    id: "routes/models";
    page: "/models";
  };
  "routes/models.create.tsx": {
    id: "routes/models.create";
    page: "/models/create";
  };
  "routes/car-templates.tsx": {
    id: "routes/car-templates";
    page: "/car-templates";
  };
  "routes/car-templates.create.tsx": {
    id: "routes/car-templates.create";
    page: "/car-templates/create";
  };
  "routes/car-templates.$id.tsx": {
    id: "routes/car-templates.$id";
    page: "/car-templates/:id";
  };
  "routes/car-templates.$id.edit.tsx": {
    id: "routes/car-templates.$id.edit";
    page: "/car-templates/:id/edit";
  };
  "routes/payments.tsx": {
    id: "routes/payments";
    page: "/payments";
  };
  "routes/payments.create.tsx": {
    id: "routes/payments.create";
    page: "/payments/create";
  };
  "routes/payment-statuses.tsx": {
    id: "routes/payment-statuses";
    page: "/payment-statuses";
  };
  "routes/locations.tsx": {
    id: "routes/locations";
    page: "/locations";
  };
  "routes/districts.tsx": {
    id: "routes/districts";
    page: "/districts";
  };
  "routes/hotels.tsx": {
    id: "routes/hotels";
    page: "/hotels";
  };
  "routes/durations.tsx": {
    id: "routes/durations";
    page: "/durations";
  };
  "routes/seasons.tsx": {
    id: "routes/seasons";
    page: "/seasons";
  };
  "routes/colors.tsx": {
    id: "routes/colors";
    page: "/colors" | "/colors/new" | "/colors/:colorId/edit";
  };
  "routes/colors_.new.tsx": {
    id: "routes/colors_.new";
    page: "/colors/new";
  };
  "routes/colors_.$colorId.edit.tsx": {
    id: "routes/colors_.$colorId.edit";
    page: "/colors/:colorId/edit";
  };
  "routes/reports.tsx": {
    id: "routes/reports";
    page: "/reports";
  };
  "routes/logs.tsx": {
    id: "routes/logs";
    page: "/logs";
  };
  "routes/contracts.tsx": {
    id: "routes/contracts";
    page: "/contracts" | "/contracts/:id/close";
  };
  "routes/contracts_.$id.close.tsx": {
    id: "routes/contracts_.$id.close";
    page: "/contracts/:id/close";
  };
  "routes/contracts.new.tsx": {
    id: "routes/contracts.new";
    page: "/contracts/new";
  };
  "routes/contracts.$id.tsx": {
    id: "routes/contracts.$id";
    page: "/contracts/:id";
  };
  "routes/contracts.$id.edit.tsx": {
    id: "routes/contracts.$id.edit";
    page: "/contracts/:id/edit";
  };
  "routes/calendar.tsx": {
    id: "routes/calendar";
    page: "/calendar" | "/calendar/new";
  };
  "routes/calendar.new.tsx": {
    id: "routes/calendar.new";
    page: "/calendar/new";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/bookings.tsx": {
    id: "routes/bookings";
    page: "/bookings";
  };
  "routes/bookings.create.tsx": {
    id: "routes/bookings.create";
    page: "/bookings/create";
  };
  "routes/bookings.$id.tsx": {
    id: "routes/bookings.$id";
    page: "/bookings/:id";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/profile.edit.tsx": {
    id: "routes/profile.edit";
    page: "/profile/edit";
  };
  "routes/my-bookings.tsx": {
    id: "routes/my-bookings";
    page: "/my-bookings";
  };
  "routes/my-contracts.tsx": {
    id: "routes/my-contracts";
    page: "/my-contracts";
  };
  "routes/my-contracts.$id.tsx": {
    id: "routes/my-contracts.$id";
    page: "/my-contracts/:id";
  };
  "routes/my-payments.tsx": {
    id: "routes/my-payments";
    page: "/my-payments";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/register-partner": typeof import("./app/routes/register-partner.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/assets.$": typeof import("./app/routes/assets.$.tsx");
  "routes/become-a-host": typeof import("./app/routes/become-a-host.tsx");
  "routes/why-choose-phuket-ride": typeof import("./app/routes/why-choose-phuket-ride.tsx");
  "routes/gift-cards": typeof import("./app/routes/gift-cards.tsx");
  "routes/contact-support": typeof import("./app/routes/contact-support.tsx");
  "routes/legal": typeof import("./app/routes/legal.tsx");
  "routes/insurance-protection": typeof import("./app/routes/insurance-protection.tsx");
  "routes/host-tools": typeof import("./app/routes/host-tools.tsx");
  "routes/carculator": typeof import("./app/routes/carculator.tsx");
  "routes/search-cars": typeof import("./app/routes/search-cars.tsx");
  "routes/company.$slug": typeof import("./app/routes/company.$slug.tsx");
  "routes/cars.$id": typeof import("./app/routes/cars.$id.tsx");
  "routes/cars.$id.checkout": typeof import("./app/routes/cars.$id.checkout.tsx");
  "routes/booking-confirmation": typeof import("./app/routes/booking-confirmation.tsx");
  "routes/booking-confirmation.$id": typeof import("./app/routes/booking-confirmation.$id.tsx");
  "routes/api.search-events": typeof import("./app/routes/api.search-events.tsx");
  "routes/api.metrics.dashboard-charts": typeof import("./app/routes/api.metrics.dashboard-charts.tsx");
  "routes/api.calendar-events": typeof import("./app/routes/api.calendar-events.tsx");
  "routes/api.car-templates.$id.features": typeof import("./app/routes/api.car-templates.$id.features.tsx");
  "routes/app-layout": typeof import("./app/routes/app-layout.tsx");
  "routes/dashboard-home": typeof import("./app/routes/dashboard-home.tsx");
  "routes/companies": typeof import("./app/routes/companies.tsx");
  "routes/companies.create": typeof import("./app/routes/companies.create.tsx");
  "routes/admin-companies.$companyId": typeof import("./app/routes/admin-companies.$companyId.tsx");
  "routes/companies.edit": typeof import("./app/routes/companies.edit.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/users.create": typeof import("./app/routes/users.create.tsx");
  "routes/users.$userId": typeof import("./app/routes/users.$userId.tsx");
  "routes/users.$userId.edit": typeof import("./app/routes/users.$userId.edit.tsx");
  "routes/cars": typeof import("./app/routes/cars.tsx");
  "routes/cars.create": typeof import("./app/routes/cars.create.tsx");
  "routes/admin-cars.$id": typeof import("./app/routes/admin-cars.$id.tsx");
  "routes/cars.$id.content": typeof import("./app/routes/cars.$id.content.tsx");
  "routes/cars.$id.edit": typeof import("./app/routes/cars.$id.edit.tsx");
  "routes/brands": typeof import("./app/routes/brands.tsx");
  "routes/brands.create": typeof import("./app/routes/brands.create.tsx");
  "routes/models": typeof import("./app/routes/models.tsx");
  "routes/models.create": typeof import("./app/routes/models.create.tsx");
  "routes/car-templates": typeof import("./app/routes/car-templates.tsx");
  "routes/car-templates.create": typeof import("./app/routes/car-templates.create.tsx");
  "routes/car-templates.$id": typeof import("./app/routes/car-templates.$id.tsx");
  "routes/car-templates.$id.edit": typeof import("./app/routes/car-templates.$id.edit.tsx");
  "routes/payments": typeof import("./app/routes/payments.tsx");
  "routes/payments.create": typeof import("./app/routes/payments.create.tsx");
  "routes/payment-statuses": typeof import("./app/routes/payment-statuses.tsx");
  "routes/locations": typeof import("./app/routes/locations.tsx");
  "routes/districts": typeof import("./app/routes/districts.tsx");
  "routes/hotels": typeof import("./app/routes/hotels.tsx");
  "routes/durations": typeof import("./app/routes/durations.tsx");
  "routes/seasons": typeof import("./app/routes/seasons.tsx");
  "routes/colors": typeof import("./app/routes/colors.tsx");
  "routes/colors_.new": typeof import("./app/routes/colors_.new.tsx");
  "routes/colors_.$colorId.edit": typeof import("./app/routes/colors_.$colorId.edit.tsx");
  "routes/reports": typeof import("./app/routes/reports.tsx");
  "routes/logs": typeof import("./app/routes/logs.tsx");
  "routes/contracts": typeof import("./app/routes/contracts.tsx");
  "routes/contracts_.$id.close": typeof import("./app/routes/contracts_.$id.close.tsx");
  "routes/contracts.new": typeof import("./app/routes/contracts.new.tsx");
  "routes/contracts.$id": typeof import("./app/routes/contracts.$id.tsx");
  "routes/contracts.$id.edit": typeof import("./app/routes/contracts.$id.edit.tsx");
  "routes/calendar": typeof import("./app/routes/calendar.tsx");
  "routes/calendar.new": typeof import("./app/routes/calendar.new.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/bookings": typeof import("./app/routes/bookings.tsx");
  "routes/bookings.create": typeof import("./app/routes/bookings.create.tsx");
  "routes/bookings.$id": typeof import("./app/routes/bookings.$id.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile.edit": typeof import("./app/routes/profile.edit.tsx");
  "routes/my-bookings": typeof import("./app/routes/my-bookings.tsx");
  "routes/my-contracts": typeof import("./app/routes/my-contracts.tsx");
  "routes/my-contracts.$id": typeof import("./app/routes/my-contracts.$id.tsx");
  "routes/my-payments": typeof import("./app/routes/my-payments.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
};