// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/register-partner": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/assets/*": {
    params: {
      "*": string;
    };
  };
  "/companies/:companyId": {
    params: {
      "companyId": string;
    };
  };
  "/cars/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/companies/create": {
    params: {};
  };
  "/companies/:companyId/edit": {
    params: {
      "companyId": string;
    };
  };
  "/users": {
    params: {};
  };
  "/users/create": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/users/:userId/edit": {
    params: {
      "userId": string;
    };
  };
  "/cars": {
    params: {};
  };
  "/cars/create": {
    params: {};
  };
  "/cars/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/brands": {
    params: {};
  };
  "/brands/create": {
    params: {};
  };
  "/models": {
    params: {};
  };
  "/models/create": {
    params: {};
  };
  "/car-templates": {
    params: {};
  };
  "/car-templates/create": {
    params: {};
  };
  "/car-templates/:id": {
    params: {
      "id": string;
    };
  };
  "/car-templates/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/payments": {
    params: {};
  };
  "/payments/create": {
    params: {};
  };
  "/payment-statuses": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/districts": {
    params: {};
  };
  "/hotels": {
    params: {};
  };
  "/durations": {
    params: {};
  };
  "/seasons": {
    params: {};
  };
  "/colors": {
    params: {};
  };
  "/colors/new": {
    params: {};
  };
  "/colors/:colorId/edit": {
    params: {
      "colorId": string;
    };
  };
  "/reports": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/contracts": {
    params: {};
  };
  "/contracts/:id/close": {
    params: {
      "id": string;
    };
  };
  "/contracts/new": {
    params: {};
  };
  "/contracts/:id": {
    params: {
      "id": string;
    };
  };
  "/contracts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/calendar": {
    params: {};
  };
  "/calendar/new": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/bookings": {
    params: {};
  };
  "/bookings/create": {
    params: {};
  };
  "/bookings/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/search-cars": {
    params: {};
  };
  "/my-bookings": {
    params: {};
  };
  "/my-contracts": {
    params: {};
  };
  "/my-contracts/:id": {
    params: {
      "id": string;
    };
  };
  "/my-payments": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/register-partner" | "/logout" | "/assets/*" | "/companies/:companyId" | "/cars/:id" | "/dashboard/*" | "/dashboard" | "/companies" | "/companies/create" | "/companies/:companyId/edit" | "/users" | "/users/create" | "/users/:userId" | "/users/:userId/edit" | "/cars" | "/cars/create" | "/cars/:id/edit" | "/brands" | "/brands/create" | "/models" | "/models/create" | "/car-templates" | "/car-templates/create" | "/car-templates/:id" | "/car-templates/:id/edit" | "/payments" | "/payments/create" | "/payment-statuses" | "/locations" | "/districts" | "/hotels" | "/durations" | "/seasons" | "/colors" | "/colors/new" | "/colors/:colorId/edit" | "/reports" | "/logs" | "/contracts" | "/contracts/:id/close" | "/contracts/new" | "/contracts/:id" | "/contracts/:id/edit" | "/calendar" | "/calendar/new" | "/settings" | "/bookings" | "/bookings/create" | "/bookings/:id" | "/profile" | "/profile/edit" | "/search-cars" | "/my-bookings" | "/my-contracts" | "/my-contracts/:id" | "/my-payments" | "/notifications";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/register-partner.tsx": {
    id: "routes/register-partner";
    page: "/register-partner";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/assets.$.tsx": {
    id: "routes/assets.$";
    page: "/assets/*";
  };
  "routes/companies.$companyId.tsx": {
    id: "routes/companies.$companyId";
    page: "/companies/:companyId";
  };
  "routes/cars.$id.tsx": {
    id: "routes/cars.$id";
    page: "/cars/:id";
  };
  "routes/dashboard.redirect.tsx": {
    id: "routes/dashboard.redirect";
    page: "/dashboard/*";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/companies" | "/companies/create" | "/companies/:companyId" | "/companies/:companyId/edit" | "/users" | "/users/create" | "/users/:userId" | "/users/:userId/edit" | "/cars" | "/cars/create" | "/cars/:id" | "/cars/:id/edit" | "/brands" | "/brands/create" | "/models" | "/models/create" | "/car-templates" | "/car-templates/create" | "/car-templates/:id" | "/car-templates/:id/edit" | "/payments" | "/payments/create" | "/payment-statuses" | "/locations" | "/districts" | "/hotels" | "/durations" | "/seasons" | "/colors" | "/colors/new" | "/colors/:colorId/edit" | "/reports" | "/logs" | "/contracts" | "/contracts/:id/close" | "/contracts/new" | "/contracts/:id" | "/contracts/:id/edit" | "/calendar" | "/calendar/new" | "/settings" | "/bookings" | "/bookings/create" | "/bookings/:id" | "/profile" | "/profile/edit" | "/search-cars" | "/my-bookings" | "/my-contracts" | "/my-contracts/:id" | "/my-payments" | "/notifications";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.companies.tsx": {
    id: "routes/dashboard.companies";
    page: "/companies";
  };
  "routes/dashboard.companies.create.tsx": {
    id: "routes/dashboard.companies.create";
    page: "/companies/create";
  };
  "routes/dashboard.companies.$companyId.tsx": {
    id: "routes/dashboard.companies.$companyId";
    page: "/companies/:companyId";
  };
  "routes/dashboard.companies.edit.tsx": {
    id: "routes/dashboard.companies.edit";
    page: "/companies/:companyId/edit";
  };
  "routes/dashboard.users.tsx": {
    id: "routes/dashboard.users";
    page: "/users";
  };
  "routes/dashboard.users.create.tsx": {
    id: "routes/dashboard.users.create";
    page: "/users/create";
  };
  "routes/dashboard.users.$userId.tsx": {
    id: "routes/dashboard.users.$userId";
    page: "/users/:userId";
  };
  "routes/dashboard.users.$userId.edit.tsx": {
    id: "routes/dashboard.users.$userId.edit";
    page: "/users/:userId/edit";
  };
  "routes/dashboard.cars.tsx": {
    id: "routes/dashboard.cars";
    page: "/cars";
  };
  "routes/dashboard.cars.create.tsx": {
    id: "routes/dashboard.cars.create";
    page: "/cars/create";
  };
  "routes/dashboard.cars.$id.tsx": {
    id: "routes/dashboard.cars.$id";
    page: "/cars/:id";
  };
  "routes/dashboard.cars.$id.edit.tsx": {
    id: "routes/dashboard.cars.$id.edit";
    page: "/cars/:id/edit";
  };
  "routes/dashboard.brands.tsx": {
    id: "routes/dashboard.brands";
    page: "/brands";
  };
  "routes/dashboard.brands.create.tsx": {
    id: "routes/dashboard.brands.create";
    page: "/brands/create";
  };
  "routes/dashboard.models.tsx": {
    id: "routes/dashboard.models";
    page: "/models";
  };
  "routes/dashboard.models.create.tsx": {
    id: "routes/dashboard.models.create";
    page: "/models/create";
  };
  "routes/dashboard.car-templates.tsx": {
    id: "routes/dashboard.car-templates";
    page: "/car-templates";
  };
  "routes/dashboard.car-templates.create.tsx": {
    id: "routes/dashboard.car-templates.create";
    page: "/car-templates/create";
  };
  "routes/dashboard.car-templates.$id.tsx": {
    id: "routes/dashboard.car-templates.$id";
    page: "/car-templates/:id";
  };
  "routes/dashboard.car-templates.$id.edit.tsx": {
    id: "routes/dashboard.car-templates.$id.edit";
    page: "/car-templates/:id/edit";
  };
  "routes/dashboard.payments.tsx": {
    id: "routes/dashboard.payments";
    page: "/payments";
  };
  "routes/dashboard.payments.create.tsx": {
    id: "routes/dashboard.payments.create";
    page: "/payments/create";
  };
  "routes/dashboard.payment-statuses.tsx": {
    id: "routes/dashboard.payment-statuses";
    page: "/payment-statuses";
  };
  "routes/dashboard.locations.tsx": {
    id: "routes/dashboard.locations";
    page: "/locations";
  };
  "routes/dashboard.districts.tsx": {
    id: "routes/dashboard.districts";
    page: "/districts";
  };
  "routes/dashboard.hotels.tsx": {
    id: "routes/dashboard.hotels";
    page: "/hotels";
  };
  "routes/dashboard.durations.tsx": {
    id: "routes/dashboard.durations";
    page: "/durations";
  };
  "routes/dashboard.seasons.tsx": {
    id: "routes/dashboard.seasons";
    page: "/seasons";
  };
  "routes/dashboard.colors.tsx": {
    id: "routes/dashboard.colors";
    page: "/colors" | "/colors/new" | "/colors/:colorId/edit";
  };
  "routes/dashboard.colors_.new.tsx": {
    id: "routes/dashboard.colors_.new";
    page: "/colors/new";
  };
  "routes/dashboard.colors_.$colorId.edit.tsx": {
    id: "routes/dashboard.colors_.$colorId.edit";
    page: "/colors/:colorId/edit";
  };
  "routes/dashboard.reports.tsx": {
    id: "routes/dashboard.reports";
    page: "/reports";
  };
  "routes/dashboard.logs.tsx": {
    id: "routes/dashboard.logs";
    page: "/logs";
  };
  "routes/dashboard.contracts.tsx": {
    id: "routes/dashboard.contracts";
    page: "/contracts" | "/contracts/:id/close";
  };
  "routes/dashboard.contracts_.$id.close.tsx": {
    id: "routes/dashboard.contracts_.$id.close";
    page: "/contracts/:id/close";
  };
  "routes/dashboard.contracts.new.tsx": {
    id: "routes/dashboard.contracts.new";
    page: "/contracts/new";
  };
  "routes/dashboard.contracts.$id.tsx": {
    id: "routes/dashboard.contracts.$id";
    page: "/contracts/:id";
  };
  "routes/dashboard.contracts.$id.edit.tsx": {
    id: "routes/dashboard.contracts.$id.edit";
    page: "/contracts/:id/edit";
  };
  "routes/dashboard.calendar.tsx": {
    id: "routes/dashboard.calendar";
    page: "/calendar" | "/calendar/new";
  };
  "routes/dashboard.calendar.new.tsx": {
    id: "routes/dashboard.calendar.new";
    page: "/calendar/new";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/settings";
  };
  "routes/dashboard.bookings.tsx": {
    id: "routes/dashboard.bookings";
    page: "/bookings";
  };
  "routes/dashboard.bookings.create.tsx": {
    id: "routes/dashboard.bookings.create";
    page: "/bookings/create";
  };
  "routes/dashboard.bookings.$id.tsx": {
    id: "routes/dashboard.bookings.$id";
    page: "/bookings/:id";
  };
  "routes/dashboard.profile.tsx": {
    id: "routes/dashboard.profile";
    page: "/profile";
  };
  "routes/dashboard.profile.edit.tsx": {
    id: "routes/dashboard.profile.edit";
    page: "/profile/edit";
  };
  "routes/dashboard.search-cars.tsx": {
    id: "routes/dashboard.search-cars";
    page: "/search-cars";
  };
  "routes/dashboard.my-bookings.tsx": {
    id: "routes/dashboard.my-bookings";
    page: "/my-bookings";
  };
  "routes/dashboard.my-contracts.tsx": {
    id: "routes/dashboard.my-contracts";
    page: "/my-contracts";
  };
  "routes/dashboard.my-contracts.$id.tsx": {
    id: "routes/dashboard.my-contracts.$id";
    page: "/my-contracts/:id";
  };
  "routes/dashboard.my-payments.tsx": {
    id: "routes/dashboard.my-payments";
    page: "/my-payments";
  };
  "routes/dashboard.notifications.tsx": {
    id: "routes/dashboard.notifications";
    page: "/notifications";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/register-partner": typeof import("./app/routes/register-partner.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/assets.$": typeof import("./app/routes/assets.$.tsx");
  "routes/companies.$companyId": typeof import("./app/routes/companies.$companyId.tsx");
  "routes/cars.$id": typeof import("./app/routes/cars.$id.tsx");
  "routes/dashboard.redirect": typeof import("./app/routes/dashboard.redirect.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.companies": typeof import("./app/routes/dashboard.companies.tsx");
  "routes/dashboard.companies.create": typeof import("./app/routes/dashboard.companies.create.tsx");
  "routes/dashboard.companies.$companyId": typeof import("./app/routes/dashboard.companies.$companyId.tsx");
  "routes/dashboard.companies.edit": typeof import("./app/routes/dashboard.companies.edit.tsx");
  "routes/dashboard.users": typeof import("./app/routes/dashboard.users.tsx");
  "routes/dashboard.users.create": typeof import("./app/routes/dashboard.users.create.tsx");
  "routes/dashboard.users.$userId": typeof import("./app/routes/dashboard.users.$userId.tsx");
  "routes/dashboard.users.$userId.edit": typeof import("./app/routes/dashboard.users.$userId.edit.tsx");
  "routes/dashboard.cars": typeof import("./app/routes/dashboard.cars.tsx");
  "routes/dashboard.cars.create": typeof import("./app/routes/dashboard.cars.create.tsx");
  "routes/dashboard.cars.$id": typeof import("./app/routes/dashboard.cars.$id.tsx");
  "routes/dashboard.cars.$id.edit": typeof import("./app/routes/dashboard.cars.$id.edit.tsx");
  "routes/dashboard.brands": typeof import("./app/routes/dashboard.brands.tsx");
  "routes/dashboard.brands.create": typeof import("./app/routes/dashboard.brands.create.tsx");
  "routes/dashboard.models": typeof import("./app/routes/dashboard.models.tsx");
  "routes/dashboard.models.create": typeof import("./app/routes/dashboard.models.create.tsx");
  "routes/dashboard.car-templates": typeof import("./app/routes/dashboard.car-templates.tsx");
  "routes/dashboard.car-templates.create": typeof import("./app/routes/dashboard.car-templates.create.tsx");
  "routes/dashboard.car-templates.$id": typeof import("./app/routes/dashboard.car-templates.$id.tsx");
  "routes/dashboard.car-templates.$id.edit": typeof import("./app/routes/dashboard.car-templates.$id.edit.tsx");
  "routes/dashboard.payments": typeof import("./app/routes/dashboard.payments.tsx");
  "routes/dashboard.payments.create": typeof import("./app/routes/dashboard.payments.create.tsx");
  "routes/dashboard.payment-statuses": typeof import("./app/routes/dashboard.payment-statuses.tsx");
  "routes/dashboard.locations": typeof import("./app/routes/dashboard.locations.tsx");
  "routes/dashboard.districts": typeof import("./app/routes/dashboard.districts.tsx");
  "routes/dashboard.hotels": typeof import("./app/routes/dashboard.hotels.tsx");
  "routes/dashboard.durations": typeof import("./app/routes/dashboard.durations.tsx");
  "routes/dashboard.seasons": typeof import("./app/routes/dashboard.seasons.tsx");
  "routes/dashboard.colors": typeof import("./app/routes/dashboard.colors.tsx");
  "routes/dashboard.colors_.new": typeof import("./app/routes/dashboard.colors_.new.tsx");
  "routes/dashboard.colors_.$colorId.edit": typeof import("./app/routes/dashboard.colors_.$colorId.edit.tsx");
  "routes/dashboard.reports": typeof import("./app/routes/dashboard.reports.tsx");
  "routes/dashboard.logs": typeof import("./app/routes/dashboard.logs.tsx");
  "routes/dashboard.contracts": typeof import("./app/routes/dashboard.contracts.tsx");
  "routes/dashboard.contracts_.$id.close": typeof import("./app/routes/dashboard.contracts_.$id.close.tsx");
  "routes/dashboard.contracts.new": typeof import("./app/routes/dashboard.contracts.new.tsx");
  "routes/dashboard.contracts.$id": typeof import("./app/routes/dashboard.contracts.$id.tsx");
  "routes/dashboard.contracts.$id.edit": typeof import("./app/routes/dashboard.contracts.$id.edit.tsx");
  "routes/dashboard.calendar": typeof import("./app/routes/dashboard.calendar.tsx");
  "routes/dashboard.calendar.new": typeof import("./app/routes/dashboard.calendar.new.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/dashboard.bookings": typeof import("./app/routes/dashboard.bookings.tsx");
  "routes/dashboard.bookings.create": typeof import("./app/routes/dashboard.bookings.create.tsx");
  "routes/dashboard.bookings.$id": typeof import("./app/routes/dashboard.bookings.$id.tsx");
  "routes/dashboard.profile": typeof import("./app/routes/dashboard.profile.tsx");
  "routes/dashboard.profile.edit": typeof import("./app/routes/dashboard.profile.edit.tsx");
  "routes/dashboard.search-cars": typeof import("./app/routes/dashboard.search-cars.tsx");
  "routes/dashboard.my-bookings": typeof import("./app/routes/dashboard.my-bookings.tsx");
  "routes/dashboard.my-contracts": typeof import("./app/routes/dashboard.my-contracts.tsx");
  "routes/dashboard.my-contracts.$id": typeof import("./app/routes/dashboard.my-contracts.$id.tsx");
  "routes/dashboard.my-payments": typeof import("./app/routes/dashboard.my-payments.tsx");
  "routes/dashboard.notifications": typeof import("./app/routes/dashboard.notifications.tsx");
};